from services.ocr.base import BaseOCRProvider
from services.ocr.tesseract import TesseractOCRProvider
from services.ocr.google_document_ai import GoogleDocumentAIProvider
from services.ocr.azure_document_intelligence import AzureDocumentIntelligenceProvider
from services.ocr.ocr_factory import get_ocr_provider, set_active_ocr_provider
