SEED_EXPENSES = [
    {"id": "exp_demo_001", "employee_id": "60d5ec49f1b29c2d18c1d502",
     "employee_name": "Pratham Employee", "title": "Client dinner at Marriott",
     "category": "Meals", "amount": 68.50, "expense_date": "2026-07-15",
     "description": "Team dinner after client meeting",
     "receipt_url": "/uploads/receipts/demo/demo_meal.jpg", "status": "Paid",
     "risk_score": "Low", "risk_flags": [], "payment_reference": "TXN-1001",
     "rule_engine": {"policy_status": "PASS", "violations": [], "risk_score": 0},
     "duplicate_check": {"duplicate": False, "similar_expense": None, "confidence": 0.0, "reason": "No duplicate claims detected."},
     "ai_analysis": {"summary": "Meals claim within policy.", "fraud_score": 8, "risk": "Very Safe", "recommendation": "Auto Approve Recommendation", "confidence": 0.97, "reason": ["Amount within Meals policy limit.", "Receipt verified.", "No duplicate claims found."], "anomaly": False, "severity": "Low", "fraud_indicators": [], "policy_sections": ["Food Policy Section 2.3"], "version_metadata": {"model": "gpt-5.5", "prompt_version": "v2.1", "policy_version": "TravelPolicy2026_v2.1", "latency_ms": 180}},
     "timeline": [{"step": "Submitted", "actor": "Pratham Employee", "timestamp": "2026-07-15T10:00:00Z", "details": "Expense submitted"}, {"step": "AI Analysis", "actor": "FinanceOS AI", "timestamp": "2026-07-15T10:00:01Z", "details": "Risk: Low · Auto Approve Recommendation"}],
     "created_at": "2026-07-15T10:00:00Z"},
    {"id": "exp_demo_002", "employee_id": "60d5ec49f1b29c2d18c1d502",
     "employee_name": "Pratham Employee", "title": "Uber to airport",
     "category": "Travel", "amount": 45.20, "expense_date": "2026-07-18",
     "description": "Rideshare to international terminal",
     "receipt_url": "/uploads/receipts/demo/demo_uber.jpg", "status": "Approved",
     "risk_score": "Low", "risk_flags": [], "payment_reference": None,
     "rule_engine": {"policy_status": "PASS", "violations": [], "risk_score": 0},
     "duplicate_check": {"duplicate": False, "similar_expense": None, "confidence": 0.0, "reason": "No duplicate claims detected."},
     "ai_analysis": {"summary": "Travel claim within policy.", "fraud_score": 5, "risk": "Very Safe", "recommendation": "Auto Approve Recommendation", "confidence": 0.97, "reason": ["Amount within travel policy.", "Receipt verified.", "No duplicate claims found."], "anomaly": False, "severity": "Low", "fraud_indicators": [], "policy_sections": ["Rideshare & Taxi Policy Section 3.1"], "version_metadata": {"model": "gpt-5.5", "prompt_version": "v2.1", "policy_version": "TravelPolicy2026_v2.1", "latency_ms": 165}},
     "timeline": [{"step": "Submitted", "actor": "Pratham Employee", "timestamp": "2026-07-18T08:30:00Z", "details": "Expense submitted"}, {"step": "AI Analysis", "actor": "FinanceOS AI", "timestamp": "2026-07-18T08:30:01Z", "details": "Risk: Low · Auto Approve Recommendation"}],
     "created_at": "2026-07-18T08:30:00Z"},
    {"id": "exp_demo_003", "employee_id": "60d5ec49f1b29c2d18c1d502",
     "employee_name": "Pratham Employee", "title": "Hotel stay – Hilton Austin",
     "category": "Accommodation", "amount": 320.00, "expense_date": "2026-07-20",
     "description": "2-night stay for annual conference",
     "receipt_url": "/uploads/receipts/demo/demo_hotel.jpg", "status": "Submitted",
     "risk_score": "Medium",
     "risk_flags": ["Amount exceeds configured category maximum limit of $250.00."],
     "rule_engine": {"policy_status": "VIOLATION", "violations": ["Hotel expense ($320.00) exceeds maximum allowance of $250.00/night."], "risk_score": 35},
     "duplicate_check": {"duplicate": False, "similar_expense": None, "confidence": 0.0, "reason": "No duplicate claims detected."},
     "ai_analysis": {"summary": "Accommodation claim over policy limit.", "fraud_score": 35, "risk": "Review Required", "recommendation": "Manager Review Required", "confidence": 0.88, "reason": ["Amount exceeds hotel policy limit of $250/night.", "No duplicate claims found.", "Receipt attached."], "anomaly": False, "severity": "Low", "fraud_indicators": ["Amount exceeds policy limit"], "policy_sections": ["Travel Policy Section 4.2"], "version_metadata": {"model": "gpt-5.5", "prompt_version": "v2.1", "policy_version": "TravelPolicy2026_v2.1", "latency_ms": 210}},
     "timeline": [{"step": "Submitted", "actor": "Pratham Employee", "timestamp": "2026-07-20T09:00:00Z", "details": "Expense submitted"}, {"step": "AI Analysis", "actor": "FinanceOS AI", "timestamp": "2026-07-20T09:00:01Z", "details": "Risk: Medium · Manager Review Required"}],
     "payment_reference": None, "created_at": "2026-07-20T09:00:00Z"},
    {"id": "exp_demo_004", "employee_id": "60d5ec49f1b29c2d18c1d502",
     "employee_name": "Pratham Employee", "title": "Office supplies – notebooks",
     "category": "Supplies", "amount": 34.80, "expense_date": "2026-06-28",
     "description": "Stationery for team workspace", "receipt_url": None,
     "status": "Paid", "risk_score": "Low", "risk_flags": [],
     "rule_engine": {"policy_status": "PASS", "violations": [], "risk_score": 0},
     "duplicate_check": {"duplicate": False, "similar_expense": None, "confidence": 0.0, "reason": "No duplicate claims detected."},
     "ai_analysis": {"summary": "Office supplies within policy.", "fraud_score": 6, "risk": "Very Safe", "recommendation": "Auto Approve Recommendation", "confidence": 0.97, "reason": ["Amount within Supplies policy limit.", "No receipt required for this category.", "No duplicate claims found."], "anomaly": False, "severity": "Low", "fraud_indicators": [], "policy_sections": ["General Expense Policy Section 1.0"], "version_metadata": {"model": "gpt-5.5", "prompt_version": "v2.1", "policy_version": "TravelPolicy2026_v2.1", "latency_ms": 145}},
     "timeline": [{"step": "Submitted", "actor": "Pratham Employee", "timestamp": "2026-06-28T14:00:00Z", "details": "Expense submitted"}, {"step": "AI Analysis", "actor": "FinanceOS AI", "timestamp": "2026-06-28T14:00:01Z", "details": "Risk: Low · Auto Approve Recommendation"}],
     "payment_reference": "TXN-0987", "created_at": "2026-06-28T14:00:00Z"},
    {"id": "exp_demo_005", "employee_id": "60d5ec49f1b29c2d18c1d502",
     "employee_name": "Pratham Employee", "title": "Lunch meeting – Starbucks",
     "category": "Meals", "amount": 22.40, "expense_date": "2026-06-10",
     "description": "Working lunch with design team",
     "receipt_url": "/uploads/receipts/demo/demo_starbucks.jpg", "status": "Paid",
     "risk_score": "Low", "risk_flags": [],
     "rule_engine": {"policy_status": "PASS", "violations": [], "risk_score": 0},
     "duplicate_check": {"duplicate": False, "similar_expense": None, "confidence": 0.0, "reason": "No duplicate claims detected."},
     "ai_analysis": {"summary": "Meals claim within policy.", "fraud_score": 4, "risk": "Very Safe", "recommendation": "Auto Approve Recommendation", "confidence": 0.97, "reason": ["Amount within Meals policy limit.", "Receipt verified.", "No duplicate claims found."], "anomaly": False, "severity": "Low", "fraud_indicators": [], "policy_sections": ["Food Policy Section 2.3"], "version_metadata": {"model": "gpt-5.5", "prompt_version": "v2.1", "policy_version": "TravelPolicy2026_v2.1", "latency_ms": 155}},
     "timeline": [{"step": "Submitted", "actor": "Pratham Employee", "timestamp": "2026-06-10T12:30:00Z", "details": "Expense submitted"}, {"step": "AI Analysis", "actor": "FinanceOS AI", "timestamp": "2026-06-10T12:30:01Z", "details": "Risk: Low · Auto Approve Recommendation"}],
     "payment_reference": "TXN-0921",
     "created_at": "2026-06-10T12:30:00Z"},
    {"id": "exp_demo_006", "employee_id": "60d5ec49f1b29c2d18c1d502",
     "employee_name": "Pratham Employee", "title": "Flight – Mumbai to Delhi",
     "category": "Travel", "amount": 480.00, "expense_date": "2026-05-22",
     "description": "Economy flight for Q2 business review",
     "receipt_url": "/uploads/receipts/demo/demo_flight.pdf", "status": "Paid",
     "risk_score": "Low", "risk_flags": [],
     "rule_engine": {"policy_status": "PASS", "violations": [], "risk_score": 0},
     "duplicate_check": {"duplicate": False, "similar_expense": None, "confidence": 0.0, "reason": "No duplicate claims detected."},
     "ai_analysis": {"summary": "Flight within travel policy.", "fraud_score": 10, "risk": "Very Safe", "recommendation": "Auto Approve Recommendation", "confidence": 0.97, "reason": ["Economy class flight within policy.", "Receipt attached.", "No duplicate claims found."], "anomaly": False, "severity": "Low", "fraud_indicators": [], "policy_sections": ["Rideshare & Taxi Policy Section 3.1"], "version_metadata": {"model": "gpt-5.5", "prompt_version": "v2.1", "policy_version": "TravelPolicy2026_v2.1", "latency_ms": 170}},
     "timeline": [{"step": "Submitted", "actor": "Pratham Employee", "timestamp": "2026-05-22T07:00:00Z", "details": "Expense submitted"}, {"step": "AI Analysis", "actor": "FinanceOS AI", "timestamp": "2026-05-22T07:00:01Z", "details": "Risk: Low · Auto Approve Recommendation"}],
     "payment_reference": "TXN-0890",
     "created_at": "2026-05-22T07:00:00Z"},
    {"id": "exp_demo_007", "employee_id": "60d5ec49f1b29c2d18c1d502",
     "employee_name": "Pratham Employee", "title": "Alcohol at client event",
     "category": "Meals", "amount": 85.00, "expense_date": "2026-07-25",
     "description": "Drinks at client networking event", "receipt_url": None,
     "status": "Rejected", "risk_score": "High",
     "risk_flags": ["Alcohol items are non-reimbursable under Food Policy Section 2.3.",
                    "Missing required receipt document."],
     "rule_engine": {"policy_status": "VIOLATION", "violations": ["Alcohol items are strictly non-reimbursable under Section 2.3 of Food Policy.", "Meal expense ($85.00) exceeds policy maximum limit of $50.00."], "risk_score": 80},
     "duplicate_check": {"duplicate": False, "similar_expense": None, "confidence": 0.0, "reason": "No duplicate claims detected."},
     "ai_analysis": {"summary": "High-risk Meals claim with alcohol and policy violations.", "fraud_score": 80, "risk": "Very High Risk", "recommendation": "Manual Investigation Needed", "confidence": 0.75, "reason": ["Alcohol is non-reimbursable per Food Policy Section 2.3.", "Amount exceeds Meals policy limit of $50.", "Missing required receipt."], "anomaly": False, "severity": "High", "fraud_indicators": ["Alcohol item detected", "Amount over policy limit", "Missing receipt"], "policy_sections": ["Food Policy Section 2.3"], "version_metadata": {"model": "gpt-5.5", "prompt_version": "v2.1", "policy_version": "TravelPolicy2026_v2.1", "latency_ms": 230}},
     "timeline": [{"step": "Submitted", "actor": "Pratham Employee", "timestamp": "2026-07-25T19:00:00Z", "details": "Expense submitted"}, {"step": "AI Analysis", "actor": "FinanceOS AI", "timestamp": "2026-07-25T19:00:01Z", "details": "Risk: High · Manual Investigation Needed"}],
     "payment_reference": None, "created_at": "2026-07-25T19:00:00Z"},
    {"id": "exp_demo_008", "employee_id": "60d5ec49f1b29c2d18c1d502",
     "employee_name": "Pratham Employee", "title": "Conference registration fee",
     "category": "Other", "amount": 120.00, "expense_date": "2026-04-15",
     "description": "React India 2026 developer conference",
     "receipt_url": "/uploads/receipts/demo/demo_conf.pdf", "status": "Paid",
     "risk_score": "Low", "risk_flags": [],
     "rule_engine": {"policy_status": "PASS", "violations": [], "risk_score": 0},
     "duplicate_check": {"duplicate": False, "similar_expense": None, "confidence": 0.0, "reason": "No duplicate claims detected."},
     "ai_analysis": {"summary": "Conference fee within Other policy.", "fraud_score": 7, "risk": "Very Safe", "recommendation": "Auto Approve Recommendation", "confidence": 0.97, "reason": ["Amount within Other policy limit.", "Receipt attached.", "No duplicate claims found."], "anomaly": False, "severity": "Low", "fraud_indicators": [], "policy_sections": ["General Expense Policy Section 1.0"], "version_metadata": {"model": "gpt-5.5", "prompt_version": "v2.1", "policy_version": "TravelPolicy2026_v2.1", "latency_ms": 160}},
     "timeline": [{"step": "Submitted", "actor": "Pratham Employee", "timestamp": "2026-04-15T10:00:00Z", "details": "Expense submitted"}, {"step": "AI Analysis", "actor": "FinanceOS AI", "timestamp": "2026-04-15T10:00:01Z", "details": "Risk: Low · Auto Approve Recommendation"}],
     "payment_reference": "TXN-0812",
     "created_at": "2026-04-15T10:00:00Z"},
    {"id": "exp_demo_009", "employee_id": "60d5ec49f1b29c2d18c1d502",
     "employee_name": "Pratham Employee", "title": "Client taxi – late night",
     "category": "Travel", "amount": 38.00, "expense_date": "2026-03-12",
     "description": "Taxi after client dinner",
     "receipt_url": "/uploads/receipts/demo/demo_taxi.jpg", "status": "Paid",
     "risk_score": "Low", "risk_flags": [],
     "rule_engine": {"policy_status": "PASS", "violations": [], "risk_score": 0},
     "duplicate_check": {"duplicate": False, "similar_expense": None, "confidence": 0.0, "reason": "No duplicate claims detected."},
     "ai_analysis": {"summary": "Taxi within travel policy.", "fraud_score": 5, "risk": "Very Safe", "recommendation": "Auto Approve Recommendation", "confidence": 0.97, "reason": ["Taxi within travel policy.", "Receipt attached.", "No duplicate claims found."], "anomaly": False, "severity": "Low", "fraud_indicators": [], "policy_sections": ["Rideshare & Taxi Policy Section 3.1"], "version_metadata": {"model": "gpt-5.5", "prompt_version": "v2.1", "policy_version": "TravelPolicy2026_v2.1", "latency_ms": 150}},
     "timeline": [{"step": "Submitted", "actor": "Pratham Employee", "timestamp": "2026-03-12T23:00:00Z", "details": "Expense submitted"}, {"step": "AI Analysis", "actor": "FinanceOS AI", "timestamp": "2026-03-12T23:00:01Z", "details": "Risk: Low · Auto Approve Recommendation"}],
     "payment_reference": "TXN-0780",
     "created_at": "2026-03-12T23:00:00Z"},
    {"id": "exp_demo_010", "employee_id": "60d5ec49f1b29c2d18c1d502",
     "employee_name": "Pratham Employee", "title": "Team lunch – Pizza Hut",
     "category": "Meals", "amount": 47.60, "expense_date": "2026-02-20",
     "description": "Monthly team lunch outing",
     "receipt_url": "/uploads/receipts/demo/demo_lunch.jpg", "status": "Paid",
     "risk_score": "Low", "risk_flags": [],
     "rule_engine": {"policy_status": "PASS", "violations": [], "risk_score": 0},
     "duplicate_check": {"duplicate": False, "similar_expense": None, "confidence": 0.0, "reason": "No duplicate claims detected."},
     "ai_analysis": {"summary": "Meals claim within policy.", "fraud_score": 6, "risk": "Very Safe", "recommendation": "Auto Approve Recommendation", "confidence": 0.97, "reason": ["Amount within Meals policy limit.", "Receipt attached.", "No duplicate claims found."], "anomaly": False, "severity": "Low", "fraud_indicators": [], "policy_sections": ["Food Policy Section 2.3"], "version_metadata": {"model": "gpt-5.5", "prompt_version": "v2.1", "policy_version": "TravelPolicy2026_v2.1", "latency_ms": 158}},
     "timeline": [{"step": "Submitted", "actor": "Pratham Employee", "timestamp": "2026-02-20T13:00:00Z", "details": "Expense submitted"}, {"step": "AI Analysis", "actor": "FinanceOS AI", "timestamp": "2026-02-20T13:00:01Z", "details": "Risk: Low · Auto Approve Recommendation"}],
     "payment_reference": "TXN-0745",
     "created_at": "2026-02-20T13:00:00Z"},
]
